# Generated by Django 3.2.4 on 2021-11-11 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='is_live',
            new_name='is_cool',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
